version: "3"
services:
  parse:
    build: ./
    ports:
      - 1337:1337
    links:
      - mongo
    command: --appId APPLICATION_ID --masterKey MASTER_KEY --databaseURI mongodb://mongo/test

  mongo:
    image: mongo
    restart: always
