apiVersion: v1
kind: Service
metadata: 
  annotations: 
    prometheus.io/scrape: "true"
  name: prometheus
  namespace: microservice
  labels:
    name: prometheus
spec:
  selector: 
    app: prometheus 
  ports: 
    - name: prometheus 
      port: 8080
      targetPort: prometheus
  type: LoadBalancer