kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: parse
  namespace: microservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: parse
    spec:
      containers:
      - name: parse
        image: kmehant/parse
        args: ["--appId=APPLICATION_ID", "--masterKey=MASTER_KEY","--databaseURI=mongodb://mongo/test"]
        imagePullPolicy: Always
        ports:
        - containerPort: 1337
          protocol: TCP
      restartPolicy: Always 