apiVersion: v1
kind: Namespace
metadata:
  name: microservice
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: microservice
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      slack_api_url: "https://hooks.slack.com/services/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"
    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 5m  
      receiver: default 
      routes:
      - match:
          team: devops
        receiver: devops
        continue: true 
    receivers:
    - name: 'default'
    - name: 'devops'
      slack_configs:
      - channel: '#alerts'
        send_resolved: true
  