apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo
  namespace: microservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          imagePullPolicy: Always
          ports:
            - containerPort: 27017 